http:
  host: 'localhost'
  port: 8080

db:
  mongodb:
    host: 'mongodb+srv://hmsp:hmsp@cluster0.lbsfr.mongodb.net/ManagementTool?retryWrites=true&w=majority'

jwt:
  secret: 'privateKey'
  expiresIn: '2419200s'
  
sendGrid:
  apiKey: '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'
  customerEmail: 'info@hmsp.com.au'
  jwt:
    secret: 'privateKeySendGrid'
    expiresIn: '1000s'

FE:
  host: 'http://localhost:3000'

app:
  limit_req: '10mb'

cloudinary:
  cloud_name: 'hmsp-cloudinary'
  api_key: '828185581879961'
  api_secret: 'AqglXRwk3NJHljaDGxjTJxJ0oZw'
  load_preset:
    avatar_staff: 'avatars'
    avatar_customer: 'avatars'
